### ISSUE TITLE
PyPi release?

### ISSUE THREAD

**Issue by benjaoming** [FelixSchwarz/anythumbnailer#2]
Hey!

This is actually quite a nice little utility!

Would you be interested in having this project on PyPi as a 0.1 version or something?

**Comment by FelixSchwarz** [comment]
That's a good idea. I should really do that.

**Comment by FelixSchwarz** [comment]
done: https://pypi.python.org/pypi/anythumbnailer

**Comment by benjaoming** [comment]
Awesome! :D
