### ISSUE TITLE
How to install anythumbnailer ?

### ISSUE THREAD

**Issue by cj044** [FelixSchwarz/anythumbnailer#5]
Excuse me sir. I am rookie. But I am very need your code.
https://imgur.com/0uCUS86
According to your message. Which one is right  put  setup.py in pycharm lib folder  or pip install in windows command  ?
Thanks

**Comment by FelixSchwarz** [comment]
You should be able to do both. Unfortunately I did not have any time in the last years to update the code. If you are not really familiar with Python development you will probably hit a few problems which might be hard to fix without coding knowledge. Also I assume there are other projects out there now which fix the problem much better than I did many years ago.

Thank you for your interest in the project though. I'm sure you could improve it a lot even with moderate Python knowledge.
